import java.util.Scanner;

import year2023.day01;

public class App {
    public static void main(String[] args) throws Exception {
        Scanner input = new Scanner(System.in);
        System.out.print("Please enter the year you want the solution for: ");
        int year = input.nextInt();
        System.out.print("Please enter the day you want the solution for: ");
        int day = input.nextInt();
        System.out.print("Please enter the part you want the solution for: ");
        int part = input.nextInt();
        System.out.print("Please enter the input: ");
        String task = input.next();
        System.out.println("=============================");
        System.out.println("Your Result: "+year2023.day01.part1("two934seven1\r\n" + //
                "8825eightknfv\r\n" + //
                "sevenoneqbfzntsix55\r\n" + //
                "foursqpqvv192rdrbtcccfourone\r\n" + //
                "9jpzhpxqthreelmrnlhfqmn4\r\n" + //
                "onedpsckg3xdhmgtsixthreefivejlncszkxeight\r\n" + //
                "4twofour\r\n" + //
                "7eighttwo17fournsmrznntgjrdpkdjvx\r\n" + //
                "573\r\n" + //
                "ninethree3\r\n" + //
                "3gngzkpkgrf\r\n" + //
                "qeightwo2xjvfkfiveone\r\n" + //
                "twoonej26\r\n" + //
                "sgoneightfoureight5sevenjzsqghg\r\n" + //
                "bnrb36xtjd7four9\r\n" + //
                "threepprhsff3prbpfivesevenseven4\r\n" + //
                "38sevennineninemnfzklttkxnine3\r\n" + //
                "8mllzkfqklhonefivemv4\r\n" + //
                "onedcqlqcrzn66three\r\n" + //
                "1fourjthreefc2gbtbdzsix\r\n" + //
                "eight7two4258\r\n" + //
                "4hmfzdzf\r\n" + //
                "26dsmdzznm7\r\n" + //
                "plckvxznnineh34eight2\r\n" + //
                "dhrvd4eightgxznhqmh\r\n" + //
                "5fxhhkghvm3nineshpcxhtwo6fourhrktpbq\r\n" + //
                "qklhmhmdlgeighttwoonetwo52five\r\n" + //
                "86threemmpchhzdvsvxfzrj\r\n" + //
                "9clvchpgrslnkhdmfkjmlrvgnf\r\n" + //
                "8ncpdtspfivethree\r\n" + //
                "gtbtkqcgvh8945\r\n" + //
                "sevencrkbt3btljpdpgstlf\r\n" + //
                "8nine37bpkmtghhnc2hnreightwohvs\r\n" + //
                "5qxmsrthreempcmpdcnnv41\r\n" + //
                "8threezrxhxgx4g\r\n" + //
                "jhsb3onep1\r\n" + //
                "eight71rnz\r\n" + //
                "7p16lrxktlr6\r\n" + //
                "8one5fivelvdbjzz\r\n" + //
                "1nine2twodhnineonesixkqfcbgdlfg\r\n" + //
                "four8sixfourfive\r\n" + //
                "pjdmt4one8sdsdhhqxlqgzpk6qrtdvxm\r\n" + //
                "sixzfourkdpmnn92qbjkjqfqpn\r\n" + //
                "42threefiveh\r\n" + //
                "5fhgzt8threemzhblb6\r\n" + //
                "bbc3kxhvbfrn8four6five\r\n" + //
                "91fknhthreefour\r\n" + //
                "six9fttmqpninethreevhgtrxklbvxbljsp1\r\n" + //
                "four5five1471mtfv\r\n" + //
                "3bjkggcntwo3ptmjhmthree7\r\n" + //
                "four2eightone\r\n" + //
                "threedrzktlgbz4five\r\n" + //
                "dmpgttqfivekcdjbf49six\r\n" + //
                "9bplkkgrxgjqjqb3seven\r\n" + //
                "4861sx4six\r\n" + //
                "hjzmxtxvxkkpbvgpvmgb4two8bqxlvponesq\r\n" + //
                "lkxxtkctlphjfivepjlrg1\r\n" + //
                "xszdbbvxjrfxs2vrmmbfourpzcfmgppk33eightwors\r\n" + //
                "966fourflbfsk3\r\n" + //
                "1bskshtjseven5qlbjhqgzhbzxvlxsvtcmmzseven\r\n" + //
                "56two28cbhfsdcjsix2four\r\n" + //
                "6s5qcmvjltqeightslhnzmvbfvcmxj\r\n" + //
                "twosevenjxk6lhrkknnkq\r\n" + //
                "kjkj2lkkldqbgzhglmthree9\r\n" + //
                "ftxhnpms1onetwoxg2\r\n" + //
                "three9sixsevenmrgggztckzgzv7\r\n" + //
                "stvgmjgnine2vvsnjhlzkstwo5szsbvzjdzb\r\n" + //
                "v6\r\n" + //
                "threetwolscvhrlmm3r\r\n" + //
                "two17kblkphfninefour6six1\r\n" + //
                "one6fiveeight9sixjzljjfknrhkzxr\r\n" + //
                "dgpqm43xthreekxgspjzrzcsix\r\n" + //
                "2two8fourpppb2\r\n" + //
                "fiveseven5four\r\n" + //
                "5rttwofivefnmbkn8nine2eight\r\n" + //
                "43threeninelgnpzrdtbc1lbkjkvqrdcd\r\n" + //
                "1seventx\r\n" + //
                "nctwonefourjzgskmxjmq2\r\n" + //
                "rpzpht2tdxczzfthreeseven\r\n" + //
                "two1seven\r\n" + //
                "6bjztkxhsixkgnkroneightht\r\n" + //
                "9mqzkgmv4vxqrpf4\r\n" + //
                "49hlj\r\n" + //
                "46gv\r\n" + //
                "75sixfddn75\r\n" + //
                "eight87xzjkdpnnjjfqeight\r\n" + //
                "9pfcdhxbcrnpsnmvkqnsqsninedgtlmmc5\r\n" + //
                "xmfbn34\r\n" + //
                "99lvrrndpqcnhznn\r\n" + //
                "qsmxhxfph24three\r\n" + //
                "lql25\r\n" + //
                "8five1dhrkm\r\n" + //
                "twoninefourcxksqfmn1\r\n" + //
                "7eightdclrvn\r\n" + //
                "one2seveneight3ninemcpnmonetwo\r\n" + //
                "33fivefivenftbczsdstlxzbp\r\n" + //
                "9r97five\r\n" + //
                "5fivessskxvnt6qqbkkqrggxg9gsdtbptpn\r\n" + //
                "threesjdpjdkczjgthree6\r\n" + //
                "twojqm86\r\n" + //
                "bttrx15qfznmdncnz5\r\n" + //
                "ppckphrtzhstd3xvthzrxxlrrjtk\r\n" + //
                "qkm6ckeight7gnmqkltz6jsrgjhbck\r\n" + //
                "zdjjjlpmjtphbjpm9threeskqrphxbfqqeightone\r\n" + //
                "konesix1three\r\n" + //
                "four24391rzxtffour\r\n" + //
                "hsevenfive36fqrbjpfj7\r\n" + //
                "dxdcssixbcnp8two639\r\n" + //
                "hnvg2\r\n" + //
                "sixeighthmqkjjsix6tbvdhzone2vsn\r\n" + //
                "dfzlxq7pjmq5\r\n" + //
                "5n3\r\n" + //
                "twovjcgxdsdngt2smfxfqxeight\r\n" + //
                "ftpjlnvg5qshclfzqtc2eightninefivecsrgk\r\n" + //
                "zzgsjsjffpvcgfmjtnpkrsqlmpzlt9four\r\n" + //
                "4btrhpznzr8oneightg\r\n" + //
                "pph2one\r\n" + //
                "5seveneighteight\r\n" + //
                "31sfrfrcgmseven\r\n" + //
                "four7bdqgrhfive3\r\n" + //
                "nbrzbggpseven9prthjvknq\r\n" + //
                "3sixonefourh\r\n" + //
                "fourgkrpkzdmhtwoseven6txplz\r\n" + //
                "four84ldbhnkxjph\r\n" + //
                "6eightonesrb\r\n" + //
                "gnmckftk62jgsjxzpk\r\n" + //
                "bzctx9onetmcnzhxkrtchjgqxv66\r\n" + //
                "1three5\r\n" + //
                "27two\r\n" + //
                "34eightwox\r\n" + //
                "6ndgrbmfkfive2ksxfbnjbl7fkrm\r\n" + //
                "kxpz4gjmgcgzzq63five\r\n" + //
                "nfvmfrbc151one8nggsdqvm\r\n" + //
                "4clnctseven5nsn5\r\n" + //
                "hcrpbvqmmdbstlxccthkththreebm6\r\n" + //
                "gdnmh6cslzhjhdl8nine\r\n" + //
                "sevenninethreefive4bgknpbnine\r\n" + //
                "2sevent6three1\r\n" + //
                "2jbrmdxgpnine7\r\n" + //
                "nshlgtbkmcmgkmqone3\r\n" + //
                "dklhc9sevenrxxzzxltsnlltqcjrbgprnx\r\n" + //
                "gmrjhlvzppmklnl39\r\n" + //
                "kv86eight3dcdpp6pmdzcvsix\r\n" + //
                "fiveseven2sevensix6952\r\n" + //
                "3xrtthnsevenjxsxpzvc\r\n" + //
                "256nmzrlzbczv\r\n" + //
                "4dp7onesixvpcf\r\n" + //
                "25onesevenonexvnst4smvlfszcrv\r\n" + //
                "lcxncproneseven37five\r\n" + //
                "ninezjsrptfivenhsqxrdz7one\r\n" + //
                "cscdmnfrcxfqdtkmhkldgjlxdjqsxslhdzvvt4\r\n" + //
                "sixfnjnfkqm67blkmnqtwo\r\n" + //
                "fivethree7\r\n" + //
                "2five5ninegcmqbkpp61npkpml9\r\n" + //
                "3qktrxninefour\r\n" + //
                "qdhmxstwo44two\r\n" + //
                "21nine\r\n" + //
                "rbnineone3xppvtbmv3sevenvxkkgmgklg\r\n" + //
                "mcvzplmpvptwo38\r\n" + //
                "sv176threeone\r\n" + //
                "5vksixqsccgdkrrfourcgnpsfxbvj\r\n" + //
                "xxtwone6eight\r\n" + //
                "threeonespkbnsj9onesevenpz5\r\n" + //
                "fivenncrfvhfdsevengxzkxbkrklgsfvllrkbx4\r\n" + //
                "69kp1seven8dqkrx\r\n" + //
                "dmb9ccghdjjpjxfivehtwo4\r\n" + //
                "6nhgdkpdone\r\n" + //
                "tfvqdqdqcszxbrdmmrninesct2\r\n" + //
                "8sevenfour2eight8rskc\r\n" + //
                "cpmgffcvln9sjdsgfivesix5rppfsfmmqtffive\r\n" + //
                "5two7\r\n" + //
                "7threecrkljthreetwo\r\n" + //
                "6qgqzsdhprd\r\n" + //
                "959zgjscgtm\r\n" + //
                "fourtwoppfrdqgtseven9\r\n" + //
                "8bbchvoneeightr\r\n" + //
                "gtddrb1rznsdjtonethree5four\r\n" + //
                "8rrskfzlmlbrsninezdzpt3\r\n" + //
                "6njhmkpp4onefive8two\r\n" + //
                "4cqpnkcxjtwoqzqmjnqccfs256hcnqpfm\r\n" + //
                "nineeightseven62sixhlxlps\r\n" + //
                "dtqplzzf87threecthree\r\n" + //
                "mqptgzjxddxgxpjr5\r\n" + //
                "9194jbjjktwofive\r\n" + //
                "five514foursevendzxlh2\r\n" + //
                "6nineeight85zvx\r\n" + //
                "four8gsgrstfmdv99hpkfgptzqkhsmgsnlggrseven\r\n" + //
                "9three298\r\n" + //
                "3fpttzk35\r\n" + //
                "rbtckzonexkqmfxrnsbsrkqbq66sixkcqfzjfour\r\n" + //
                "sixkdcrrrppcsix399fccnsbhfxvfiveft\r\n" + //
                "xfjxbfvmbxbf3twokkcfrbcfbmkmhghsbzf\r\n" + //
                "9sixonesix3lqqf9\r\n" + //
                "eight3fourgcmp\r\n" + //
                "xjccxkhkvgltzqslmseven5twoqhcmpsixeightnine\r\n" + //
                "62eight8\r\n" + //
                "hzhccdkxb336\r\n" + //
                "gcsbmkdfmqvxtfj81\r\n" + //
                "two445nine\r\n" + //
                "xhrkgql8six41nine1\r\n" + //
                "5dnlcsjb\r\n" + //
                "jdqdg8gtgrctwo4fourthree\r\n" + //
                "five4five\r\n" + //
                "3threecggvthjv6\r\n" + //
                "sevenzrjzqhgtvtqvkp3three5sixhxdmfour\r\n" + //
                "2249eight6\r\n" + //
                "drt5trhdjqf3fourfourkfour4\r\n" + //
                "5oneone1\r\n" + //
                "threeseven5six\r\n" + //
                "45bclsgsqx\r\n" + //
                "6ggfjqls\r\n" + //
                "rhpmhfournrzg418onevlkcxxdrd\r\n" + //
                "fcvgszpsixthreegqqctvdqnfrbnlbmknlvgfour1\r\n" + //
                "twoxvrhmxjbbn2eight\r\n" + //
                "27eighteightsevensix6six\r\n" + //
                "veightwosix54bcvvtcgbqfzprp7four2\r\n" + //
                "9kthreeqntgvbb34693\r\n" + //
                "zxcdmfg48ftlhk\r\n" + //
                "1mhcctbmbzmfivefourtwo3\r\n" + //
                "two6vxsdfhgstslsix\r\n" + //
                "threesixmzhvfqsix5xhrhrvsfh7kpcrsp\r\n" + //
                "oneggkztrmsgrthree536three\r\n" + //
                "7seveneight81ronesix\r\n" + //
                "sixllrjlqtffqvtdjqhctt66four3twoone\r\n" + //
                "2zxqpgmgz\r\n" + //
                "7rfngpqkqgfivetwojf\r\n" + //
                "vvbfnnine3ngv\r\n" + //
                "59sixninelmhmqchlthkbpthree33\r\n" + //
                "1three6seven1seven5qntpbnsfour\r\n" + //
                "7nfzfsdxzfive8fjvllc4\r\n" + //
                "56seven5seven\r\n" + //
                "1fivegqbrdgths\r\n" + //
                "four32vmhvnk\r\n" + //
                "hvdjnmpqvqbnrcrclkgkrfseven6lgrvthv\r\n" + //
                "28xngctrvmnc4ntvxhmxfsj13\r\n" + //
                "onep1onecjjmxxtd\r\n" + //
                "9eightwof\r\n" + //
                "hzgmtfdj8nine7seven\r\n" + //
                "eightseven3\r\n" + //
                "fivepnhlninefive1lcftks\r\n" + //
                "122ninelrgmdgmqzd\r\n" + //
                "zjsix3\r\n" + //
                "7rffvg9hbjpx\r\n" + //
                "3h76\r\n" + //
                "fouronessbhxlcclkzmnnbksixlcdqtf3\r\n" + //
                "4fivesix228five\r\n" + //
                "sixrlthree1bzhddfbkrgxpgxfivef\r\n" + //
                "dxgqnkqfgq8\r\n" + //
                "onemcfourbmkhh5px\r\n" + //
                "fmtqjcbxznine3three\r\n" + //
                "qzkcxvnffg1gmhplhlffgtwo3onevg7five\r\n" + //
                "twokj7xv63six\r\n" + //
                "four58\r\n" + //
                "fvjeightwosixrbrgnmrrmdtwomseven69seven\r\n" + //
                "5fivefour\r\n" + //
                "6pg8twomrqfzkxrthree9\r\n" + //
                "7xqtqfrpprlvhnthree\r\n" + //
                "l35sevencreight4\r\n" + //
                "threechpctdgtq8fxspqtnvggkxtmeighteighthdgngnmc\r\n" + //
                "one16twosix\r\n" + //
                "threetwofour3eight1pvgcthree\r\n" + //
                "229\r\n" + //
                "ngcnthreeone7hqbbntqxeightkgtc\r\n" + //
                "qtgkz1ntone68\r\n" + //
                "nine2seven\r\n" + //
                "two1jjccnlrqlsdfvtgjmmhh5prfpcc\r\n" + //
                "onesixvtbjgdqmtg1eight\r\n" + //
                "77qkvdszsp9ctqndxzrjc\r\n" + //
                "rnldvcmks74355\r\n" + //
                "fourkljgznpqntwofoureightlc3zmljfnqnr\r\n" + //
                "8threetbv6cdjjbtmmxcfour4qlqjql\r\n" + //
                "jfkvbvjxjzk7\r\n" + //
                "7eight8vhsdrd\r\n" + //
                "onezdgffrmz2\r\n" + //
                "eightseven8\r\n" + //
                "7gjdsevenjsdkljn2fv\r\n" + //
                "kmst4\r\n" + //
                "3five8smctrhdhfninelzbrszmbdm\r\n" + //
                "fiveseven4ninevdfive3\r\n" + //
                "8jg6nine4jmmsbpbnskoneqxgjrphhf\r\n" + //
                "mgfourfour3hgmrzkntjm2hxrrfsghnone\r\n" + //
                "ninecqmg72\r\n" + //
                "ldthtljblpl3fiveonervtxnxczfx2\r\n" + //
                "9sevencsevennscmbjgthree\r\n" + //
                "7lnj9four\r\n" + //
                "fgtwonexmkvkcgpq36sixsmfnxjs\r\n" + //
                "qgmfmnh6twoeight\r\n" + //
                "56sqrseven\r\n" + //
                "183877\r\n" + //
                "ntt1seveneight513\r\n" + //
                "7three6dzdrs\r\n" + //
                "8sixsevenfour\r\n" + //
                "mzfhdnhseven4eightvjsdnxlonenfzlcxr\r\n" + //
                "sixzdczsbtq29one4eight6\r\n" + //
                "jmxcbmktjzeight5fivenhtzfsdqbx\r\n" + //
                "four2rvlppone258\r\n" + //
                "fivezvlqr236nine\r\n" + //
                "262\r\n" + //
                "58six2nineone5\r\n" + //
                "twoeighttwo3ktzhmdvlx\r\n" + //
                "64nsjgqsqkhfqmfk\r\n" + //
                "foursx18\r\n" + //
                "gklzjvvv93zzmzgpn\r\n" + //
                "onenmcvr6\r\n" + //
                "qsnmlbmlr6\r\n" + //
                "sbtwonesevenfourhgltwofzhzmbsrfm6two\r\n" + //
                "8fdhxeighttpcjkkmgsgnpnvsix2eighttwo\r\n" + //
                "5pvxnxxdfourfour75\r\n" + //
                "85vtsgkn1kfzkszmbld4cpgrqsfive\r\n" + //
                "sdbzkzp1dq5lk\r\n" + //
                "28161twodfznxckr\r\n" + //
                "xfpgnrlfour61\r\n" + //
                "kzkkp65qtqfppc7f9\r\n" + //
                "twospplzdrdfvsixsnldtwotwo29six\r\n" + //
                "9fpbm\r\n" + //
                "3one83dlvdr\r\n" + //
                "9rvbtwo25sixkzlxfkg9\r\n" + //
                "8jbmfbfsxrnxk7oneninesix\r\n" + //
                "3798\r\n" + //
                "jhcqmfive9\r\n" + //
                "nine35\r\n" + //
                "596\r\n" + //
                "nvzztnine2vhhchqkzfjzmkgjbzlxhvtdhddnr\r\n" + //
                "5bltnjlmt12threenh2\r\n" + //
                "eight5sevenninepgxvhflb4eightmxv\r\n" + //
                "xtrct7fournfivefourfive\r\n" + //
                "dhbpsnpxsglnt5vsnclxhnntt61two\r\n" + //
                "twoonekntsmsd81fourfourfive\r\n" + //
                "gpnceightdx5pklsp79x\r\n" + //
                "four5fszlnphhxvhgbmfcdkdbgbc7\r\n" + //
                "xbxtjllpr9threeninesixbbtkn6\r\n" + //
                "p7\r\n" + //
                "nine644two5\r\n" + //
                "5zzzlmspbcx9vfdllvqtl8five\r\n" + //
                "four2bxmrthree\r\n" + //
                "7rhgfnzqbpgmpnfz\r\n" + //
                "threejhfmbmxzp469\r\n" + //
                "74ninebmtpfkzbcg5nine\r\n" + //
                "fflpg34two25lvnmxvqlv\r\n" + //
                "jtqtnthxqflp2onesix39\r\n" + //
                "9sevenninefd8qpfiveseven\r\n" + //
                "28mb5\r\n" + //
                "lflcphkxqqnzhd2five\r\n" + //
                "3seven4fftnss\r\n" + //
                "ninezxhxqxxpblm9\r\n" + //
                "4ninevgpmxxmqlf8\r\n" + //
                "sevenfiveonesevenfjccpmnnninesix3nine\r\n" + //
                "qmkvt6pxbdcbrcsrgppzptzchkmone\r\n" + //
                "2sixone\r\n" + //
                "6dzskdbknpsix\r\n" + //
                "twonpqfsvbmqgeight23ct\r\n" + //
                "4sevensxdzsfbmmmdrdjtpbh\r\n" + //
                "sxkpmmhsix9five7\r\n" + //
                "fnxtgfrltwo67threepvbsixzvj\r\n" + //
                "54jmvmdbkltqsixtmccscsixeight\r\n" + //
                "6fivefourrbshbc82jrfm2\r\n" + //
                "dhlpvhzhms6\r\n" + //
                "419bhbcdsvftxfvvkxcxprksjs4\r\n" + //
                "sqrq17nine\r\n" + //
                "84rjcbktz8hrplcqsvhqqnnqnsevencjhone\r\n" + //
                "gkmljdk2dgrlptkxdsix3four599\r\n" + //
                "cnjpf818sevennine\r\n" + //
                "8cvg\r\n" + //
                "3jqbbpfpxmpkrhfoursix\r\n" + //
                "9zkrhbmzkbzlcnxlgdsixthree8\r\n" + //
                "nine9kvxeight2zqvzhgjzjz\r\n" + //
                "fourbglmlqzgvzhjrmz2nzqxlqseven\r\n" + //
                "seven4five8nine44eight\r\n" + //
                "onegnine6\r\n" + //
                "qeightwosixfivesevenzmjfrqvnsbnqlt7four\r\n" + //
                "eightvrshp9xnxlgqcnninegvbj\r\n" + //
                "ninelpbvs9three8ltzvxnd4\r\n" + //
                "nmnlzone3grqbzcdnpxsbcbzxn4fjptnsrqsqgsdcv\r\n" + //
                "18fourcqfive1gccxg\r\n" + //
                "gfglone6bqsqjmlftcqpqmmqmglskzfourvkhd9\r\n" + //
                "5cxgkn1g\r\n" + //
                "29seven9ppr\r\n" + //
                "fiverkmhxvnbp3lvpeight1one\r\n" + //
                "77four5dsdqzvt\r\n" + //
                "gvvpbone23\r\n" + //
                "twolrjs56one\r\n" + //
                "six2745six\r\n" + //
                "kbxplzpsixsevenseven5one3\r\n" + //
                "threexzrcfgffkjsix9zgdseven56\r\n" + //
                "onetrqcfl6\r\n" + //
                "three23nine\r\n" + //
                "four2mv\r\n" + //
                "xzfnzkmeightthn6twotwoeightqmf\r\n" + //
                "hxxxldcvj99three5qgmllbtrsq\r\n" + //
                "6zcszjbrzjpgrvfivemnzkpbq2six\r\n" + //
                "6zvtsixone73three\r\n" + //
                "threeflxtwo5fivefhbjptgfjmgbhpmbjmsv\r\n" + //
                "5nineeightfourd\r\n" + //
                "five26five7sixthree1three\r\n" + //
                "fzvsixsix3mxxhseven\r\n" + //
                "twoccxdqqkdvc2two9ps6threefour\r\n" + //
                "447lkkoneonefour6rx\r\n" + //
                "8seveneightwox\r\n" + //
                "sgjv21\r\n" + //
                "soneightkmtps8onesixvpsdcfbbz\r\n" + //
                "8pzrtoneffhg\r\n" + //
                "mmzeight631\r\n" + //
                "5fonefive\r\n" + //
                "foursgx8fiveltczmccpzx\r\n" + //
                "sevensdbhnpmjninetwovlv1three\r\n" + //
                "64qrjdtpxbxdbcqmmlqtnine6sevenfxhcrjnine\r\n" + //
                "1seventhree\r\n" + //
                "ktmfour3\r\n" + //
                "fournine8skzxtftwo9h9\r\n" + //
                "bjq8\r\n" + //
                "mrshhhzsixcxsxxmbh1bone9fivelsplqv\r\n" + //
                "7threezvgxdvrthree7227\r\n" + //
                "znnvfive5mctxdfive3j4\r\n" + //
                "five2three8\r\n" + //
                "gdtdqc9nine1\r\n" + //
                "three3eightgnsxrmbmxld9six\r\n" + //
                "zsgmcpxxvseven7onetwoseven6\r\n" + //
                "8n3919hfiveoneightf\r\n" + //
                "3rfrzmlfsjxthreefour\r\n" + //
                "dnnshdvxdl6onendg27\r\n" + //
                "66lpbz\r\n" + //
                "sevenlkjpxthree5\r\n" + //
                "8clqlplvljone5hfh81\r\n" + //
                "fourldvjsixfourfour5xrmcnf\r\n" + //
                "9nine2\r\n" + //
                "4one1\r\n" + //
                "4vzjgncrztvstcf9one4\r\n" + //
                "four37\r\n" + //
                "4sixlqpnqxqtrhpc3\r\n" + //
                "8threejzg\r\n" + //
                "znxccm8\r\n" + //
                "one8eighteightkcvnqjpsp6nine\r\n" + //
                "fivesixgc74oneseventhreesix\r\n" + //
                "5twohshtsdtqk2\r\n" + //
                "hzmchfourvzjgnt2threetwo5cgfld\r\n" + //
                "one9three836one8nk\r\n" + //
                "ssslsdftjfgkpzkln5\r\n" + //
                "xhsxxkzk1x2tzbjthsnsix\r\n" + //
                "8nineeight3njq\r\n" + //
                "ninethree5eightbfour2\r\n" + //
                "five56sixclxjqsjseven8eight\r\n" + //
                "three3cninenz\r\n" + //
                "lt3onevpkgsixsix\r\n" + //
                "4pkbmgtwo6zmvn71eight7\r\n" + //
                "2eight6cdd83\r\n" + //
                "5kvp3zhzq\r\n" + //
                "vtcmdkkcmnmf1two\r\n" + //
                "nine2nponeoneseven\r\n" + //
                "xm1twofoursevenfoureight\r\n" + //
                "ggkvsljtddcmznlxlqb4one32oneightppn\r\n" + //
                "onehdq785\r\n" + //
                "vzthreezjbdrlvhglbbcvlfk5\r\n" + //
                "eight9smt1sixsevenckqxlbvdzone\r\n" + //
                "one7fdcbzjtfhbps9oneonetfftbneight\r\n" + //
                "3sixfgqbsngnd1zmqbxfllbp\r\n" + //
                "roneight28one8fpzmkhvdhbqlrfive\r\n" + //
                "4five2four453ttlvfqxb\r\n" + //
                "five2four413hhnts8six\r\n" + //
                "xlfpxbzrbphb3one\r\n" + //
                "eightone8nineeight\r\n" + //
                "1zprfttxqmtbhzckcfoursix2threenine\r\n" + //
                "7sixzqrjxn92pnbfxzbrnmvrnpjpdone\r\n" + //
                "pvlfeight1xkgrvczlcfvvl8kzcktkjbj\r\n" + //
                "four7phjzlzn3two3two9seven\r\n" + //
                "1tkcdvdtj7nqfsrnmfzghmkrqeight\r\n" + //
                "36fourxfdgrprrdgmjczxb\r\n" + //
                "five5fivefdkgnkfgd5\r\n" + //
                "5seven5sxlkbldznz53three8tmkzlrt\r\n" + //
                "8dkxkfvjkprxtjlh5tjvjm2glkpbmhjd\r\n" + //
                "seventwo3\r\n" + //
                "bgssljzld2one5seventhree4\r\n" + //
                "sixfourrqzdbdhhhc7lkxqbtsseven55\r\n" + //
                "6threegtwo7fivesrbvfk\r\n" + //
                "2mpxkrtjphdseven\r\n" + //
                "14seven9dkk\r\n" + //
                "85dmtjqkchp7two4\r\n" + //
                "hvqfbchqhpbggrqhf4ps\r\n" + //
                "dzdknbdceight72fourcmfvsrzt\r\n" + //
                "xmvgjjfourfourmjmkh5onefive8\r\n" + //
                "qdfreighteightninecdxrtdbd7\r\n" + //
                "mxlhxlbvbndqfzmseven34four\r\n" + //
                "432three5vqhmjzgvghnhhg\r\n" + //
                "ghczftpkttwo4sixoneone4brf\r\n" + //
                "kbbzcpsqsl7qdlgff5fourfive6jk\r\n" + //
                "v8nxzpjxntcbtwonrcgztsthree1eightpfdsp\r\n" + //
                "7zjdzbnrpltfivemgcsjzrdjskhfmbgvlr5dl\r\n" + //
                "9kpbzzr\r\n" + //
                "8386six3mzh3\r\n" + //
                "41nineeightfive\r\n" + //
                "twotwo5threebvgmmhqrlqltqmndhveightsix2\r\n" + //
                "58drxrgkklm\r\n" + //
                "8two48six3sixthtwo\r\n" + //
                "eight88msfnone87nine\r\n" + //
                "four5lvxfhktrconexqzqvl\r\n" + //
                "six8mrlccbeightonejnzbdkm4one\r\n" + //
                "oneseveneight366xzqmnmfvvrph\r\n" + //
                "joneight7nine7five\r\n" + //
                "5fourtwo26onefivegsnbcjj\r\n" + //
                "cpjnvhnzxsevendbnblfkpx44lzn88\r\n" + //
                "zfmdcsfkktwogxmrsbtwo2six78\r\n" + //
                "ninetwo59foursevenoneightsx\r\n" + //
                "vjbbphb5dddvksevenpmnmtjvzdvxkkbcqxbb\r\n" + //
                "9ccgtrznm4\r\n" + //
                "zplpfivesixkjfdvrv6rfmqk\r\n" + //
                "hfxhpsxgxjfdbfmjb6one\r\n" + //
                "threethree9\r\n" + //
                "six3seven\r\n" + //
                "seven286\r\n" + //
                "bnkrghgbkzdz29two31\r\n" + //
                "gvlzrhntvseven3\r\n" + //
                "twosevengdkzgv6\r\n" + //
                "rddtz12five9znvtsljztbztprthreeszkfhh\r\n" + //
                "nfivesevenhfpklnxqb4nineonermtfsk\r\n" + //
                "zzz2onegpthree4fdnqxrtcnh8\r\n" + //
                "4xchnsevenxnkbrdpzsnine6\r\n" + //
                "hveightwofourfive8\r\n" + //
                "8one3\r\n" + //
                "7chfpsbh1two\r\n" + //
                "two2eight5gchbxqvrmdfqvghtnjssix1\r\n" + //
                "zfbeightwo3\r\n" + //
                "qhjnfxpfoursix9five\r\n" + //
                "8fourrbrrjqqph\r\n" + //
                "five5threethreezfvskmsv76\r\n" + //
                "sixvtjnktt4\r\n" + //
                "5cndcht2fivebdnxcnzzmfninenineqzktj\r\n" + //
                "qfzclldsvzvcdqfxhtqqtknine527\r\n" + //
                "onefjrmmfqvgnxnjdtkdmk25zghnp\r\n" + //
                "hvddcjnoneeightnine9eight\r\n" + //
                "9lxpszk\r\n" + //
                "17fourfiverfnbmkrxlvone\r\n" + //
                "qxvdlrxq89vf\r\n" + //
                "qeightwotwo2\r\n" + //
                "rzmxzgnzljzssnxscvv9seven2kbnineseven\r\n" + //
                "sevenseven8\r\n" + //
                "rkhkone8four\r\n" + //
                "zn68\r\n" + //
                "5pvfjmjxthreeninevtj88\r\n" + //
                "51dtwo5ngvxnmjeightgbhzxbd\r\n" + //
                "two6kxkvscbxcg34six3\r\n" + //
                "qbn1\r\n" + //
                "hgxgtwoqtmsqbv3\r\n" + //
                "threethreejmtjk18two\r\n" + //
                "sixone4fourseven6zcgpdqps\r\n" + //
                "fiveqptd8gtjfour1twothree\r\n" + //
                "89fivefive4\r\n" + //
                "sixvnvmdmfeightcbbvbrkffqstwo7\r\n" + //
                "three4fivefive5klxvsbhslzsix29\r\n" + //
                "two9sixhncrcvxmf\r\n" + //
                "rsp146\r\n" + //
                "eight2jtvps\r\n" + //
                "7four6\r\n" + //
                "77p1znpskm\r\n" + //
                "bbdvfhqmxddlsvdpmtvctnine135\r\n" + //
                "dlclxtkxk85bn\r\n" + //
                "bxbjslnrfk6\r\n" + //
                "51zfrtvmcbkkrnd7\r\n" + //
                "27fivetwobbssnklg\r\n" + //
                "twojxdksqkm9ninejninekcbdgnsq3\r\n" + //
                "nineninebsbd8\r\n" + //
                "sevensevenggddbfxqrmonethree744\r\n" + //
                "srtbzcbsmfivetwothreejvzjzxqm1tjnjldcxnine\r\n" + //
                "nbsix32\r\n" + //
                "25144spnmfvvj1dxpqmhsldk\r\n" + //
                "5two4mrqnpxzs7foursevensevenr\r\n" + //
                "fourk9zszmnbvmkdrz\r\n" + //
                "lpqseven2seven\r\n" + //
                "hcjgtjcxh1dskx\r\n" + //
                "ssrnf2ninenine6ngbhfhdqsnine\r\n" + //
                "cz82jhmgn14cktblcl\r\n" + //
                "kxjzflkkbx53nine62one\r\n" + //
                "hbcnpbmfour1two\r\n" + //
                "ckjksxthree346pjtr\r\n" + //
                "ccslpmqnine27twodr\r\n" + //
                "cptwo5twoggmrjvl15eight\r\n" + //
                "4vlktln5kqfsnvrbjbszqzclmnkxseventhreefive\r\n" + //
                "one2eightwopp\r\n" + //
                "2sixsixone5\r\n" + //
                "klvsngvv38tcxvhpdhh5\r\n" + //
                "fivefllgljkdg9ndlkpbmgbrndqbpxqdk\r\n" + //
                "7ppkvstbtnvseventhreessd1three9\r\n" + //
                "threepnrcmb3\r\n" + //
                "thrqrcmzpzt7nine1three\r\n" + //
                "jvgrqgbcshhlnqrl2vrlppxbnjfrdtwofbsdvt\r\n" + //
                "rnhninezxbrlmnlczqnneightsix9one\r\n" + //
                "ghvqdxkqqfthree17\r\n" + //
                "dthreeseven2\r\n" + //
                "rkxfthree7nmfive6\r\n" + //
                "6vhnh\r\n" + //
                "13brdgbrdsvthreethreerttfkr\r\n" + //
                "ninelgfdc7\r\n" + //
                "88z9vzscqthkgnhmztjnhthreeseven\r\n" + //
                "1nine3mtgrfive8nine1\r\n" + //
                "thh5fivezfmtlsnvtdkfour34\r\n" + //
                "26six6cbjdssevenq2tl\r\n" + //
                "gxxnhsxqvjcvssrbrhbst6sixvcchxstbpb1ppqdbx\r\n" + //
                "vninexhkjkmzvhfpvcd7ninezzldthree\r\n" + //
                "2twozknrxvcsj\r\n" + //
                "3193spfourxcbdnf\r\n" + //
                "84six4vc1eightsix\r\n" + //
                "zljb46four6six\r\n" + //
                "sixfive2seven1\r\n" + //
                "1fbmq9fourmhbzzkhctp6ninenine\r\n" + //
                "onefourtworckjqzhqseven5seven\r\n" + //
                "five973knlxmtmdone8prtqlsltwo\r\n" + //
                "2ncgbgpq\r\n" + //
                "3eightthreepknbcs58three6\r\n" + //
                "6fivesrgqxhnzfouroneqpmgpmzgfoureight\r\n" + //
                "mphrj33five\r\n" + //
                "8sixfives26sdscdjtpchmh\r\n" + //
                "four64mtlxmnsjbtdkpmf4\r\n" + //
                "onefivenine9nine81two\r\n" + //
                "vfc9nqttbmbdkonegclxcgbxkx87t\r\n" + //
                "sqnzdrcs8sevensix6sixdjcmk6\r\n" + //
                "7npppqmrmblzjqckk8fourbpxlbtwonine\r\n" + //
                "nbkklkvpl2smlqbh\r\n" + //
                "37eighttwo17fh77\r\n" + //
                "eight7ninekkbvtwo\r\n" + //
                "eight18cmzzdpgl5\r\n" + //
                "sixdc17nine9ghzpdpnxcbxvztcrd\r\n" + //
                "fourfivelrmch54\r\n" + //
                "jbqbpzxbbdfiveeight9jnzfdh5xfmhhrkrkds\r\n" + //
                "146two6fourclmcllhl\r\n" + //
                "222dqgtptqqn\r\n" + //
                "gvhninesevenfiveonefcvnlmfcvjvf5\r\n" + //
                "9xgljlphcxeightfivehpdlfrmd1fmqhrnvbzboneightjd\r\n" + //
                "8sf3five6eight\r\n" + //
                "zrprbc8\r\n" + //
                "gqb6sixninerpsrpnlldteightgn\r\n" + //
                "2jdlxzk\r\n" + //
                "hfrbqn4zbpxqb81tlfxgxdvzz91\r\n" + //
                "qtdnxgmjjstlc1nndsnbbcdm6nine\r\n" + //
                "z7twonezp\r\n" + //
                "two17sevenljskthntjzxpkjrkc\r\n" + //
                "fivelvfive948\r\n" + //
                "sninehxqlkmv7oneonedbdvztzgh8\r\n" + //
                "2fourxcrkrcvn\r\n" + //
                "clh4four5htj\r\n" + //
                "hdkx4eighteightsix1kgtbb\r\n" + //
                "nlbsqhkltvmzs2njschfbmsl3fivensztjtwobxkfn\r\n" + //
                "fnrg3837five\r\n" + //
                "vxcldjmjxxcqntqcqnninefivestbbjvptfvkbr9onetwo\r\n" + //
                "4six7two\r\n" + //
                "8five5sevenslfqtblfiveone\r\n" + //
                "26ninemhvqkjgcvflplncfsixtwo\r\n" + //
                "7eight523\r\n" + //
                "9fiveplfdp1qhqhj15t\r\n" + //
                "three3eightrzvccr4h\r\n" + //
                "9vhmkkjfhtfjtwotwotkfvlhvs\r\n" + //
                "vxoneightczdfl4\r\n" + //
                "3one2\r\n" + //
                "threeeightfive2four\r\n" + //
                "gksfxtb4\r\n" + //
                "1jjgdldklznbktwo59\r\n" + //
                "761sxvprrzj2kxsmlmtpbqseven\r\n" + //
                "681q\r\n" + //
                "84ctsbf1six\r\n" + //
                "fivetwomfgplcfgfive7one1vgbz\r\n" + //
                "rfnqnnmsdcj6foureightfjfkphqpktwo\r\n" + //
                "9vntpmfsevensevenfour\r\n" + //
                "7zvchbn6two9five\r\n" + //
                "fourseven7\r\n" + //
                "2lvtkkbhtjeightfour89\r\n" + //
                "5nine5threemgsd\r\n" + //
                "933nxone5threeone\r\n" + //
                "2dtbbmghgxvkmtvnlgsxjlgbc\r\n" + //
                "1mcrlzhvzrc2\r\n" + //
                "ftwonegsndgxmbzn6one\r\n" + //
                "916vfvzvh8twolvhvlc34\r\n" + //
                "dtk7eight6c6\r\n" + //
                "kbhjg6qkdgh8rqlmstq4\r\n" + //
                "eightseven8\r\n" + //
                "bhlhcphznb92two\r\n" + //
                "q8d\r\n" + //
                "375sevenvhrhkbtbvncmqqmpxdhqzzggvr\r\n" + //
                "9onefour1nhmjb\r\n" + //
                "hqckpzrvgmgqjmvsrjhqx8twodgxkbh\r\n" + //
                "5grdsbtp6onezrkdvpdqt2\r\n" + //
                "tdgkr4\r\n" + //
                "foureight24\r\n" + //
                "ktds45zvjd\r\n" + //
                "eighttwo58lldklbmxn91fvlqllnxl\r\n" + //
                "threefive3bdmfbrhfklhxjvdgjxbp1\r\n" + //
                "hqpfgvk56oneone8\r\n" + //
                "two32fivetwo1nklfhjfffthree\r\n" + //
                "77jggmjkbqone\r\n" + //
                "6fckfqeight\r\n" + //
                "fivetwo8\r\n" + //
                "7five7threethreeb\r\n" + //
                "twosvbzfmv1fourtwoeightsixfive\r\n" + //
                "ninehninebgjnknth5bhzqlvthree6\r\n" + //
                "onefrdv3one1\r\n" + //
                "five35\r\n" + //
                "four3three3six9four55\r\n" + //
                "xbssqpvjnine9six9threefivetwomjdvmpxrh\r\n" + //
                "ctroneighttwofive3npxgbhfsix1rjnl\r\n" + //
                "8ckbzlmsbfxdn\r\n" + //
                "51gckxqqbnkntmvx1ltfmdvnlcjnine\r\n" + //
                "eight7gkql5\r\n" + //
                "sixjghxscppnfive23284\r\n" + //
                "eight7pgqxvsix\r\n" + //
                "46eightrjhgdmvf5\r\n" + //
                "four4bmjzzjqp1rv523twonevm\r\n" + //
                "3sixseven81oneeightwocr\r\n" + //
                "sixmmnqkrfplg7ztrpsixone4six\r\n" + //
                "1sixfive5nhrq9\r\n" + //
                "six8threeoneckbvqc9mzhb6nine\r\n" + //
                "33sixdfzmds12jcvfour6\r\n" + //
                "1cdlflvqhrkqpktdnnsx7six8eight7\r\n" + //
                "8four18\r\n" + //
                "tpfourvblonez8six\r\n" + //
                "fourone2smjpvclnine\r\n" + //
                "99zdtdpbbvhnninefourvzfmzbscdldhxtcjfh\r\n" + //
                "fzjeightwoeightnineseven6\r\n" + //
                "twonine2\r\n" + //
                "fourseven1eight\r\n" + //
                "2x3one\r\n" + //
                "qbjc1jtnbpdbr2six3\r\n" + //
                "sglmt84five5nine\r\n" + //
                "sixnljjqh4foursix\r\n" + //
                "4nxjgs79six\r\n" + //
                "lhkpzgzjr3z7\r\n" + //
                "onefourflllxbtkpvgfive2\r\n" + //
                "sixrdr1twoeight165\r\n" + //
                "1dxvjdhzb76915\r\n" + //
                "44pxzzttvdc185txvrpxq\r\n" + //
                "4fourfgllhzfz\r\n" + //
                "nxssptkdldkpchnseven9522nine\r\n" + //
                "nine7fivefivefffvqpvsqzsvnvlzfvfs2seven\r\n" + //
                "bzphzhgf2xrlqjgonefour3bclmhtlzbmddrq\r\n" + //
                "vsxf7eightzzndgfourfour\r\n" + //
                "rqbhb14eightthreethreevkjzhjlkcmfive\r\n" + //
                "sbkrlm3nine\r\n" + //
                "zkzlqfbzscndtlmn14four9bsscd\r\n" + //
                "six33\r\n" + //
                "1gbcgnpfnseven7plppdqone3smljtjlkhj\r\n" + //
                "9jsmdjshtzm92stx9onesd\r\n" + //
                "51four4two3one1\r\n" + //
                "bxkpcpcntkflxccsixseven1threengtrrp\r\n" + //
                "4dsdllkqnpxglbseight\r\n" + //
                "7threetd3onefour\r\n" + //
                "3vcnzndxfhfzvncfivefllrqvndtx964x\r\n" + //
                "nineeight1eightgqnzfhqkzgvfvctwo1\r\n" + //
                "6fourthreeseveneight\r\n" + //
                "eighteighttrhtplssvjnnkkreight4sixoneseven\r\n" + //
                "43hqrtctwotwo\r\n" + //
                "kcxfvhjksix3six2jbkrlmtwoseven\r\n" + //
                "43sevenpvqh9eight7xcbvnckrkshdx\r\n" + //
                "sixfive3745three\r\n" + //
                "hmxfmzqdpfzjjzdxsix8472qcpbrsgx3\r\n" + //
                "threelnzgs96five1\r\n" + //
                "1dftdbtgjrpfive3cztvmxkcxh\r\n" + //
                "pmrfive4jxfxq1\r\n" + //
                "eightclrzz981492\r\n" + //
                "mscl2eight3\r\n" + //
                "twovb8four7sevenfourkmzpdmpgxj\r\n" + //
                "59onefourxnmptgtcone\r\n" + //
                "6gsvxlbqspvzpsq\r\n" + //
                "eightthreesixtworcmpjkfvnsevenseven1six\r\n" + //
                "ghmflkhprkthsix9\r\n" + //
                "441fourfcvxonefourhg5\r\n" + //
                "four795seven\r\n" + //
                "tone11\r\n" + //
                "22seven9two\r\n" + //
                "5seventwo2\r\n" + //
                "fiveone6h\r\n" + //
                "936sevensixnine1lkp\r\n" + //
                "62kvhcg\r\n" + //
                "six19\r\n" + //
                "td25\r\n" + //
                "9two2four4fourmeight\r\n" + //
                "one6twosevencrthreeseven97\r\n" + //
                "1kttqbqkzvvr7265six\r\n" + //
                "65rzmfpfqjtzb11m1eight\r\n" + //
                "seven1rrhpxjqtp\r\n" + //
                "plktlvxkpkndhx66fivefivexkh\r\n" + //
                "tttwonefournine9oneonesplmp5d\r\n" + //
                "gkbl1fbn3two97onetwo\r\n" + //
                "1seventqngll\r\n" + //
                "dqfiverscjjrk7\r\n" + //
                "4sixfour4onethreecvbj\r\n" + //
                "24x6qhgtsxtrfh\r\n" + //
                "h6\r\n" + //
                "fourfour3three\r\n" + //
                "8hrdbnvxgndthhpmrgm\r\n" + //
                "ggzjfour8pxdlpx\r\n" + //
                "rnsixnine9fivensxfzzgzlseven\r\n" + //
                "sqzseven7\r\n" + //
                "rcpkzht5\r\n" + //
                "jxhtrkzl7eight3eightn68eight\r\n" + //
                "eightfive24\r\n" + //
                "kgxv7kclnsscsmqtnmv\r\n" + //
                "foursix2chgckldprp3zqntzscxfc\r\n" + //
                "sixsixfourone3tnbpxbmgqccncgxxnine\r\n" + //
                "oneeightkgsbdthreefivepvrsktvhrnine5s\r\n" + //
                "4vtpzghfsj\r\n" + //
                "7four1lttzxpzcbtqqdthreek\r\n" + //
                "five76\r\n" + //
                "vlqvvdhhnfzfssvthree3ccsdjhgc3seven\r\n" + //
                "2nine8six\r\n" + //
                "lddxjsczqkd26g5jpvdlfour\r\n" + //
                "1twotwofcl\r\n" + //
                "sltfz55knrfvhhbbeightsevenninesevenfour\r\n" + //
                "27155bvv\r\n" + //
                "dxjzmftwo2vnljlsthree3three\r\n" + //
                "twoqdpzhjhbzksix49dhdfq\r\n" + //
                "three2fivenineqbxkgfivefour\r\n" + //
                "qnpsfq8twoonevsjffive9\r\n" + //
                "gqvvmhxgx6gdsqmgccrmzrzltwo81szbnbkxt\r\n" + //
                "2one1czgjvtcgxfivenqsfourthreethree\r\n" + //
                "ppcspzrnnssvnht9hdfoursix\r\n" + //
                "mmqrzdkmt7sjqgsrq9rhxpgpsixgkjflnht\r\n" + //
                "57foursixfive4fourfive\r\n" + //
                "tjrfj3qldspjklvdtcb6ninefivejmbntcthree\r\n" + //
                "cgjnhsixsixsixfive7\r\n" + //
                "eightqdqgjppcfive7fivexznfsmtk\r\n" + //
                "fivefive864scrf\r\n" + //
                "six95five17threeslktfgd\r\n" + //
                "77mrrjzc1cbnkxfkxcdmxsmtwonet\r\n" + //
                "sxmsjccjrseven45\r\n" + //
                "kjpsn1eightccctxthreevvffseveneighttwo\r\n" + //
                "5twoneqr\r\n" + //
                "3threemvlqpvhdqgtqseight\r\n" + //
                "jqrxrqlz93ninesmppvdhtxk5five8\r\n" + //
                "threesixsntqreight593nine9\r\n" + //
                "fouroneznpfive6qmn8\r\n" + //
                "eightfive3sixxrrjgzlb\r\n" + //
                "gds345twotwotnjrnhjxdz\r\n" + //
                "27nprk7\r\n" + //
                "eight1three2onefourcfctvmhnqlfour\r\n" + //
                "1fourvjgkpdrsj4kd2ncd\r\n" + //
                "nine85ncsqbrmdtxbtrjxgztq\r\n" + //
                "twonineeightonerdnkjkrbpsbzcpone5\r\n" + //
                "nine8lkkvxfvlsixseven\r\n" + //
                "49three9\r\n" + //
                "jqmzthzjjseven5\r\n" + //
                "seventwo9z7four5twohstlzjx\r\n" + //
                "bzvbvsix7\r\n" + //
                "2five4\r\n" + //
                "fourthreesevenfour2nine1fivezspphbmjv\r\n" + //
                "7skjhonejhklktvzjflnineonemmgvnnine\r\n" + //
                "pmgxshqpjhn9qptllp\r\n" + //
                "2nine5\r\n" + //
                "fourqpzjrtttssthsxsq1jkrlnkk\r\n" + //
                "eight53njhcfhbjfthree3ksgrrj\r\n" + //
                "cgmvkqlcgzgfqxmgkfdzxxnxjgsd6eighttvggmfbdvztwo\r\n" + //
                "onefour8txkkpvfourzbhpsnrzleightseveng\r\n" + //
                "49z2six591one\r\n" + //
                "768five\r\n" + //
                "xgkfonethreexnlcptbgxhnine4fivetwosix\r\n" + //
                "6ghccxxjponelmxeight4\r\n" + //
                "3ninedlkvcbfmd2ktmjxsgdgr\r\n" + //
                "3threefourxcgnxhkqkjbdzb\r\n" + //
                "49eight44rlhg83gktmtm\r\n" + //
                "fnbnnpvcthrsjxnqdn9\r\n" + //
                "ldrfhknine3394lgvseightwoj\r\n" + //
                "zmpsc3lzlkmqjc5eightthree\r\n" + //
                "llpmmfsmt8llknhrn\r\n" + //
                "onedvc3sixxx9four\r\n" + //
                "148eightq6\r\n" + //
                "95one9sevenfourfour79\r\n" + //
                "one9eight78gnrthxbn\r\n" + //
                "95xzzlpjzqdtonezfntwo6sixf\r\n" + //
                "eight1sevenn8bgnmnxbmdk\r\n" + //
                "1sixseventhree2\r\n" + //
                "twogjprzznd9sixsevencpfbh1\r\n" + //
                "gnbtwomtltppkxxtwonlfxsbzjtt4bjlfxlqhlx\r\n" + //
                "three5oneoneqd3bcjgl\r\n" + //
                "pzngtc2four4811\r\n" + //
                "nnlqscgg8nine7vst4three\r\n" + //
                "fourcdqc7vvqhpgqlkjsevenfivefiveseven\r\n" + //
                "5sixtwo9sixqmxxgjvjqjtworlzpv\r\n" + //
                "6dkknsmfmnq\r\n" + //
                "2two74five7\r\n" + //
                "four3vvfskp\r\n" + //
                "qqvpdttrfiveseven6\r\n" + //
                "tbgeight8eightsix976\r\n" + //
                "sevenninetwo3jdone\r\n" + //
                "three6seven7nine82\r\n" + //
                "fxffmkjn2sevensix\r\n" + //
                "5xzbf4bjqfrfourpjhscxz\r\n" + //
                "5eighttwoeight7fivex1bnfpr\r\n" + //
                "1j3262\r\n" + //
                "two1fvxchkcdtqctph\r\n" + //
                "vgnrqn4three\r\n" + //
                "plzrk3tmqpxnhpkq6four\r\n" + //
                "four5eightone6threedbnjkvjvzxl\r\n" + //
                "bxcqcdnjjsz66gnxbhcct2nfhqlbs\r\n" + //
                "twovvqb9pxrxkmflzqeight\r\n" + //
                "86\r\n" + //
                "eight9eightsevenone2\r\n" + //
                "dclk16seven\r\n" + //
                "lzs15four\r\n" + //
                "265ninetzpnbxzllkq\r\n" + //
                "ttldqsnineffpplcxmbvknkmtdbzlsix7sbkvqhn77\r\n" + //
                "eightgxzcjvgmtgzc9gndqxbxnsktvp\r\n" + //
                "mpqxldjnfive1pzvxbqqtwonine\r\n" + //
                "gzbczdrqkmtm3lzrhnf\r\n" + //
                "mlbsfqvrrtcrvhjjbs5\r\n" + //
                "fiveljrcn27\r\n" + //
                "bvnxlsfmv6eightnine3rhsb\r\n" + //
                "five5five\r\n" + //
                "eight31zztkhrznmkbx2kvzl4eight\r\n" + //
                "fvccqgfzsqfour453125frz\r\n" + //
                "xxf5threefourtq58\r\n" + //
                "stvfjpj1ggnzgcfzldd2hbxmbgtftpskbtqmgv\r\n" + //
                "11cbcps6\r\n" + //
                "dltxch6onenzsmqbfn4onezkdntjzpc4\r\n" + //
                "4eightthreej7lpqbvzz\r\n" + //
                "sevenlgonexmrmtfhqpfourp7\r\n" + //
                "hjjdgtldrfivednsfdnmn24vtqgxk\r\n" + //
                "41tnjbxk2gghb\r\n" + //
                "2eightwotg\r\n" + //
                "eightkvhkzfivesixtcnpsxssvveight2\r\n" + //
                "59dnmmpone6mzqlnf8dvnone\r\n" + //
                "kfvqrgv87trlninedf\r\n" + //
                "85bnxlhdrmjt\r\n" + //
                "zvzxt4pzlnbb\r\n" + //
                "jfour6lpvvvbdn76tbblfqtwo\r\n" + //
                "lnqpscgkone1\r\n" + //
                "mcnfzmvzkxp1\r\n" + //
                "threeseven9onepvqhgdxcxmhtkxxvlhqrnine\r\n" + //
                "sixrzrjcmbpppcvf1bvbhblrmz\r\n" + //
                "6tzthree7sevenlm9\r\n" + //
                "four3gkqrmpgnjltwo\r\n" + //
                "threetctttrh3\r\n" + //
                "ctcfljkgm7bcphzxzjj7sb43zdkvkddktwo\r\n" + //
                "sixzjkxlfourhqtwonbslgpt9vljz1\r\n" + //
                "sgz5\r\n" + //
                "vrrfjbjpsevenzbqcnthreelhxjqmdd2\r\n" + //
                "sfmjnbnnpvthreedbsh7six5\r\n" + //
                "twovdjqdtrxg5\r\n" + //
                "nineeight7five\r\n" + //
                "4xlpdvlvonekqmqvcqjsevennsd\r\n" + //
                "fiveblbxxjcbhxvnkfd9one7twoninebj\r\n" + //
                "xdxp54sixseventwo\r\n" + //
                "onefive7\r\n" + //
                "ppgsqgjfourfourfivegtbrlkdvs1jl\r\n" + //
                "twotwoeight6sqlmffdm2three\r\n" + //
                "cvszcvq8eight\r\n" + //
                "79three\r\n" + //
                "44fivembtdfivetwones\r\n" + //
                "zqkthreefoureightthreethree2five\r\n" + //
                "74twotwo\r\n" + //
                "six6fnjz1plxb19\r\n" + //
                "mkfj72nine\r\n" + //
                "seven1nine5fourqsgrj\r\n" + //
                "5fntdgbzkjfhxlqrzcq7\r\n" + //
                "six9lgddrhjc9\r\n" + //
                "1zfzp7\r\n" + //
                "2lmncxvxbbsix7jbjrjsnvx1nine\r\n" + //
                "6eightseven3\r\n" + //
                "5vsqhnone\r\n" + //
                "xoneight3j\r\n" + //
                "1gxvbbhfdmsthxgrvnm\r\n" + //
                "sixthreeone13\r\n" + //
                "2three8bzbbd\r\n" + //
                "3dsix1\r\n" + //
                "24kmxnlpqxgpsevenfoursixfour\r\n" + //
                "fqpzqphmczcvlf2mxqvxnfqxthreeone\r\n" + //
                "eight789eightnhsh67\r\n" + //
                "zznxlmhgr3eight\r\n" + //
                "beightwolgnb4997fgx35dt\r\n" + //
                "four1dsgpfzltwo57threefivetwo\r\n" + //
                "xnjjvmlkkgsht99\r\n" + //
                "1sixhhqkx9\r\n" + //
                "eightdhmgqjflthone44eight\r\n" + //
                "9ftzbdsdkd9plrrtwo\r\n" + //
                "vhbvd8h\r\n" + //
                "txxonemsfshdrpc15onefive1four\r\n" + //
                "qgbd4eightrqxlznbjqxmxgmbrnvh7jkd\r\n" + //
                "eighteighttwofive5jsqkgm\r\n" + //
                "89hn\r\n" + //
                "3lzfjpcthreeonenine\r\n" + //
                "hkpc2sixdfldx1\r\n" + //
                "3two72jbxttzfcv\r\n" + //
                "mmkjmmlvcxxvtwo25nine2\r\n" + //
                "8751gphkmsvsjhvkzfc\r\n" + //
                "one8kmcktvzgdninegkl\r\n" + //
                "twokpxphkbjctqdcvf63one3prfive\r\n" + //
                "twotsxhbppfjcpkdfourfiveseven8sixn\r\n" + //
                "3fouronebnclssixfour6eight\r\n" + //
                "cmdgcsix1\r\n" + //
                "2eighttdqsjdrtwolmvpxqgxhd5five\r\n" + //
                "one7ninefivesevenqvpf5xmccsseven\r\n" + //
                "2n7xbptnkxzcninedhhpdcsqkc\r\n" + //
                "5n\r\n" + //
                "1kfv4821\r\n" + //
                "pslpmthreethreeone29tlmgj\r\n" + //
                "sixsevenlhn1\r\n" + //
                "nine9twoqrdgdxxfsevenmjseven\r\n" + //
                "rkrdlnjknine62\r\n" + //
                "f3\r\n" + //
                "6zzrfxdxseventhree\r\n" + //
                "265one\r\n" + //
                "seven3lbcvjxqhhdpzkttqsixjzzjjbclfq1fiveeightwojx\r\n" + //
                "seightwoone8qxcfgszninesvfcnxc68\r\n" + //
                "strqnb5eightbpnkcjdz6\r\n" + //
                "fiveninebtpbpjqbgx2bmjrgmprnd\r\n" + //
                "sixgtxr2fourrdkjg\r\n" + //
                "fivebxsevensixone872dlx"));
        System.out.println("=============================");
    }
}
